from django.db import models
from django.contrib.auth.models import User


# This is for the resume result

class ResumeResult(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="resume_results"
    )

    # Uploaded resume
    filename = models.CharField(max_length=255)
    file = models.FileField(upload_to="resumes/")
    url = models.URLField(blank=True, null=True)

    # Job requirements used for analysis
    role = models.CharField(max_length=150)
    description = models.TextField(blank=True, null=True)
    required_experience = models.PositiveIntegerField()

    # Complete result generated by AssignAccordingToExt()
    text_info = models.JSONField(default=dict)

    # Ranking generated by FileMessage()
    rank = models.PositiveIntegerField(blank=True, null=True)
    score = models.FloatField(default=0)
    match_percentage = models.FloatField(default=0)
    top_missing_skill = models.CharField(
        max_length=150,
        blank=True,
        null=True
    )

    # Error, if this particular resume failed
    error = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.filename} - {self.score}"
