# Generated by Django 6.0.7 on 2026-08-04 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resumes/')),
                ('url', models.URLField(blank=True, null=True)),
                ('role', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_experience', models.PositiveIntegerField()),
                ('text_info', models.JSONField(default=dict)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('match_percentage', models.FloatField(default=0)),
                ('top_missing_skill', models.CharField(blank=True, max_length=150, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_results', to='api.user')),
            ],
        ),
    ]
